services:
  agenda:
    container_name: agenda
    build: .
    image: agenda:latest
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 5000:5500
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agenda.rule=Host(`agenda.mirai.local`)"
      - "traefik.http.routers.agenda.entrypoints=web"
      - "traefik.http.services.agenda.loadbalancer.server.port=5500"

networks:
  traefik-net:
    external: true
