services:
  agenda:
    container_name: agenda
    build: .
    image: agenda:latest
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 5000:5000
    volumes:
      - ./agenda:/agenda
    restart: unless-stopped
    networks:
      - agnet

networks:
  agnet:
    name: agnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/24
